### PR TITLE
Added travis file (copy of industrial_core)

### PR DESCRIPTION
**Pull request by shaun-edwards**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Travis fails, but it seems that is due to a problem in IRCv2:

```
[industrial_robot_client:make] /usr/bin/c++  -fPIC   -shared -Wl,-soname,libindustrial_robot_client_bswap.so -o /home/travis/ros/ws_industrial_experimental/devel/.private/industrial_robot_client/lib/libindustrial_robot_client_bswap.so CMakeFiles/industrial_robot_client_bswap.dir/src/v1/joint_relay_handler.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v1/robot_status_relay_handler.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v1/joint_trajectory_downloader.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v1/joint_trajectory_streamer.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v1/joint_trajectory_interface.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v1/robot_state_interface.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v1/utils.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v2/joint_relay_handler.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v2/robot_status_relay_handler.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v2/joint_trajectory_streamer.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v2/joint_trajectory_interface.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v2/robot_state_interface.cpp.o CMakeFiles/industrial_robot_client_bswap.dir/src/v2/utils.cpp.o  -L/home/travis/ros/ws_industrial_experimental/devel/.private/simple_message/lib  -L/opt/ros/indigo/lib -lindustrial_utils -lsimple_message_bswap -Wl,-rpath,/home/travis/ros/ws_industrial_experimental/devel/.private/simple_message/lib:/opt/ros/indigo/lib: 
[industrial_robot_client:make] /usr/bin/ld: cannot find -lindustrial_utils
[industrial_robot_client:make] collect2: error: ld returned 1 exit status
```

looks like a missing dependency declaration.

**Review by gavanderhoorn — APPROVED** [review]
PR is ok, travis failing due to package that is being tested.

That should be fixed in other (a) PR(s).

**Comment by shaun-edwards** [comment]
Thanks for the review...still can't figure out why things failed.  It all succeeds on my system.  I even downloaded `catkin_tools` to see if that was the difference (I'm sold on catkin tools BTW)

**Comment by gavanderhoorn** [comment]
Not sure either. There is still some trickery with some pkgs not being linked by their exported libraries, so perhaps something broke.

**Comment by gavanderhoorn** [comment]
> I'm sold on catkin tools BTW

welcome to the future :artificial_satellite: ;)

**Pull request merged**
