### PR TITLE
Fix travis tests

### PR DESCRIPTION
**Pull request by mathias-luedtke**
This should fix 
```
Errors     << industrial_robot_pkg_gen:install /root/catkin_ws/logs/industrial_robot_pkg_gen/build.install.000.log
error: [Errno 21] Is a directory: 'src/industrial_robot_pkg_gen'
CMake Error at catkin_generated/safe_execute_install.cmake:4 (message):
  
  execute_process(/root/catkin_ws/build/industrial_robot_pkg_gen/catkin_generated/python_distutils_install.sh)
  returned error code
Call Stack (most recent call first):
  cmake_install.cmake:133 (INCLUDE)


make: *** [install] Error 1
```

### CODE REVIEW

**Comment by mathias-luedtke** [comment]
I had to restrict the number of parallel test jobs.
I guess it would be better to apply https://github.com/ros-industrial/industrial_core/pull/160

Update: I have tried it, but it wasn't stable: https://github.com/ipa-mdl/industrial_experimental/tree/port-issues

**Comment by mathias-luedtke** [comment]
Not sure if the `scripts` option should be used in `setup.py`.

**Comment by gavanderhoorn** [comment]
Thanks.

Should 60bc28a be reverted then, if it didn't help?

**Comment by mathias-luedtke** [comment]
> Should 60bc28a be reverted then, if it didn't help?

It helps!
Otherwise [no test will pass](https://travis-ci.org/ros-industrial/industrial_experimental/builds/229617528).
However, it would be better to fix the tests to be run in parallel.
The [patch from `industrial_core`](https://github.com/ipa-mdl/industrial_experimental/tree/port-issues) might need some adaptions to the new code, it does not solve all issues.

**Comment by gavanderhoorn** [comment]
Ok. I thought the bit about "I had to restrict the number of parallel test jobs." was stricken through, but it appears I was mistaken.

Thanks for the work again. 👍

**Comment by mathias-luedtke** [comment]
> Ok. I thought the bit about "I had to restrict the number of parallel test jobs." was stricken through, but it appears I was mistaken.

No,you weren't mistaken.. In between I thought that it is not needed anymore because of the other patches, but it wasn't stable. So I rolled the changes back.

**Comment by mathias-luedtke** [comment]
It is still [unstable](https://travis-ci.org/ros-industrial/industrial_experimental/jobs/229670410#L1503) :-/
```
/root/catkin_ws/src/industrial_experimental/IRC_v2/simple_message/test/utest_message.cpp:502: Failure

Value of: pt.addGroup(grp)

  Actual: false

Expected: true

/root/catkin_ws/src/industrial_experimental/IRC_v2/simple_message/test/utest_message.cpp:515: Failure

Value of: pt.addGroup(grp)

  Actual: false

Expected: true

[  FAILED  ] DynamicJointPt.assignment (1 ms)
```

**Comment by gavanderhoorn** [comment]
Hm.

Well, at least the Travis config is ok now.

Fact that the tests are failing is a bit of a SEP at this point for me.

**Comment by gavanderhoorn** [comment]
Ticketed it.

**Pull request merged**
